### PR TITLE
Rewrite

### PR DESCRIPTION
**Pull request by troybetz**
Final PR for rewrite & 5.0.0 release

### CODE REVIEW

**Comment by troybetz** [comment]
@tjallingt this look good to you? We're all set after this

**Comment by tjallingt** [comment]
Just ran through everything and it looks great; all tests pass and lint doesn't complain :smile: 
I ran a quick `npm update --save` to make sure almost (check below) everything is up to date.

```
D:\Github\react-youtube>npm outdated
Package               Current  Wanted       Latest  Location
babel-eslint            4.1.6   4.1.6  5.0.0-beta6  react-youtube
eslint-config-airbnb    0.1.1   0.1.1        2.0.0  react-youtube
```
Not sure what is up with `babel-eslint` beta6 being tagged as the latest release and `eslint-config-airbnb` has some breaking changes apparently so I didn't want to touch it right before a possible release...

Lastly kudos for #48 @goto-bus-stop, it never crossed my mind to import the functions and shave some weight off the package... :+1:

**Comment by goto-bus-stop** [comment]
@tjallingt the NPM `--save` flag saves everything as dependencies and not devDependencies, so 3d0bb04 added all devDependencies as normal dependencies as well.

looks like only devDependencies were actually updated, so `npm update --save-dev` should work instead.

Rest LGTM, thanks a lot :v:

**Comment by tjallingt** [comment]
Sigh... I see it now :cry:

I think that is not supposed to happen; I understand separating `--save` and `--save-dev` but why would you make `--save` update the devDependencies to the normal dependencies?

Ill revert and `npm update --save-dev` for now...

**Comment by tjallingt** [comment]
Sorry for the trouble guys. :sob: 

It seems that because of a mistake on my side while updating my node modules `npm` got confused and just dumped all the `devDependencies` in the `dependencies` list. It turns out (after just deleting the node modules folder and rerunning `npm install`) that all dependencies are completely up to date after all :+1:.

Anyway this means that as far as I can tell everything is ready for release... 

Quick, before I accidentally screw up again :fearful:

**Comment by troybetz** [comment]
Haha it's all good dude, don't even worry about it! Releasing now, thanks for all the help  🎉

**Comment by tjallingt** [comment]
My pleasure, going to try the release asap :P

**Pull request merged**
