### PR TITLE
Rewrite tests

### PR DESCRIPTION
**Pull request by troybetz**
Rewrote tests using mocha & jsdom, and added a travis ci config

### CODE REVIEW

**Comment by troybetz** [comment]
cc @tjallingt, can you see if these run on your machine?

**Comment by tjallingt** [comment]
```cmd
D:\GitHub\react-youtube>npm run test

> react-youtube@4.1.2 test D:\GitHub\react-youtube
> mocha



  YouTube
    V should render a div with a custom id (205ms)
    V should render a div with a custom className
    V should create and bind a new youtube player when mounted
    V should load a url
    V should load a new url
    V should load a url with autoplay enabled
    V should destroy the youtube player


  7 passing (261ms)
```
Seems good to me :P 
I assume the first test takes so long because it's loading the YouTube Iframe API.

**Comment by troybetz** [comment]
Sweet! and ahh yeah I tried that but `defaultProps` are set on the class, not the instance so every instance of `react-youtube` would have an id of 'player_1'.

**Comment by tjallingt** [comment]
>Why className but not id?

I kinda wrote the same thing twice: i just meant why have a defaultprop for `className` but not for `id`. And when using a default prop for `id` why not set it to the `_.randomId`

**Comment by troybetz** [comment]
Ah ok, I just put an empty default string for `className` because it doesn't have to be random, can take it out though. And for `id`, the random id has to be generated inside an instance, so I couldn't put it in `defaultProps` or else every instance of `react-youtube` would have the same id.

**Comment by tjallingt** [comment]
Ah okay, well that is fine I guess...
Personally I leave `className`, `id` and `style` out of `defaultProps` as they are usually less relevant to the actual functioning of the component (and them not being set is generally also no problem).

**Comment by troybetz** [comment]
mmm that's a good point, I'll take it out and revise the tests right now. Aside from that, everything else looks good?

**Comment by tjallingt** [comment]
Yea it looks great :)
Tests in general are kind of like magic to me though, I should really brush up on them sometimes...

**Comment by troybetz** [comment]
Removed `className` from default props & merged!

**Pull request merged**
