### PR TITLE
Fixed playerVars start and end not working correctly

### PR DESCRIPTION
**Pull request by tjallingt**
Also added a test for the start and end time handling

This should fix issue #52

### CODE REVIEW

**Comment by goto-bus-stop** [comment]
Works here!

As for that `opts` object, you could do something like:

```js
const opts = { videoId: id }
// ...
  if ('start' in playerVars) {
    opts.startSeconds = playerVars.start
  }
// ...
```

But it doesn't really matter much, it works either way.

**Comment by tjallingt** [comment]
@goto-bus-stop ugh thats a great solution,  ill rewrite it like that when i have time... (funny how you can sometimes miss the most obvious solutions)

**Comment by goto-bus-stop** [comment]
:+1:

**Comment by troybetz** [comment]
Sorry, thought y'all had merged this already! LGTM, go for it

**Comment by goto-bus-stop** [comment]
Mind pushing an NPM release for this? :) If you have time!

**Pull request merged**
