### PR TITLE
Reuse youtube player instead of discarding and reinstantiating

### PR DESCRIPTION
**Pull request by tjallingt**
Using the `youtube-player` wrapper the `react-youtube` component now uses the api methods to load a new video.
See issues #26, #29 and #36

### CODE REVIEW

**Comment by tjallingt** [comment]
Things that are on the todo list at the moment:
* changing the `opts` on the component won't update them
  * if `opts` change the component will need to be destroyed and re-instantiated, the `youtube-player` module should make this quite easy.
* changing the `onError` and `onReady` props on the component won't do anything
  * changing them to be called by internal methods should fix this.
* tests are completely broken
* some dependencies are out of date and might benefit from getting updated
  * update to `react` ^0.14.0
    * use `react-dom` and `react-addon-test-utils` for the tests
  * `babel` just released ^6.0.0 which is a major overhaul
  * `jest` and `eslint` have newer versions (and the airbnb lint file got updated as well)

**Comment by tjallingt** [comment]
Have not tested any of these new changes yet so I'm unsure to what extend they will work as intended :S 
I'm going to clone this into my quick test app later to confirm everything works :)

**Comment by tjallingt** [comment]
Finished testing the features... It seems that all is working just fine :D 

One thing that does annoy me is that the youtube api is apparently very picky with its urls when it comes to `loadVideoByUrl` and `cueVideoByUrl`. It seems that the url needs to be in this format: `http://www.youtube.com/v/VIDEO_ID?version=3`.
Personally I'm a fan of just getting rid of the url prop in favour of a `videoId` prop but it would be pretty easy to use `get-youtube-id` to strip the id off an url passed to the url prop and put it in the correct url...

I don't know whether I should concern myself with updating the dependencies... as far as I can tell nothing would really break so it might just be worth it...

What do you think @troybetz?

**Comment by tjallingt** [comment]
Should have `git commit --amend` that last one :S 
I have too little expertise to rewrite the tests so I think it's ready to be merged... @troybetz?

**Comment by tjallingt** [comment]
Should have `git commit --amend` that last one :S 
I have too little expertise to rewrite the tests so I think it's ready to be merged... @troybetz?

**Comment by troybetz** [comment]
You're a legend! This is looking very good, definitely try updating the dependencies if you want. 

Also agreed re: videoId vs url, in the future let's drop `props.url` & add `props.videoId`? Would remove get-youtube-id dependencies and move react-youtube closer to youtube-player API. But let's wait on that, and get back to full previous functionality first, and then start making changes to the public API.

Only thing I'm not very comfortable with is detecting `props.opts` changes, I'd really like us to get back to full previous functionality before changing things up so would you mind removing that just for now? My fault for not making that clear before, otherwise this is genuinely fantastic. 

Will give this a final once over after removing `props.opts` changes, and then merge. Don't worry about the tests I'm going to rewrite them w/ mocha afterwards

**Comment by troybetz** [comment]
Don't worry about the commit history, we can just squash them all into one commit when ready

**Comment by tjallingt** [comment]
> Only thing I'm not very comfortable with is detecting props.opts changes, I'd really like us to get back to full previous functionality before changing things up so would you mind removing that just for now? My fault for not making that clear before, otherwise this is genuinely fantastic.

Okay so that means that if the `props.opts` update the player will just ignore it? that'd need to be clearly documented in the readme but I'd be fine with that as well (especially as the reloading of the player is strange behaviour...)
Gimme a sec to commit the new changes :P

**Comment by tjallingt** [comment]
Ill keep `underscore` in there because it could be useful in the future.

**Comment by troybetz** [comment]
Yep! It may end up changing in the future though, need to check if the actual YouTube iFrame API reloads if anything other than videoId changes

**Comment by tjallingt** [comment]
pressed the wrong button
My mistake

**Comment by tjallingt** [comment]
As far as I can tell previous functionality has been fully restored now! :smile: 
Possible future changes (in a different pull or w/e) could be: 
* using `props.videoId` instead of `props.url` (and getting rid of `get-youtube-id`)
* reloading if `opts` change (depending on behaviour of YouTube Iframe API)

**Comment by troybetz** [comment]
Sweet, going to check it out in depth right now, will comment back when finished!

**Comment by troybetz** [comment]
Ok, everything is working amazingly for the most part! Just a couple of very small changes to make and it's ready for merging.


- Let's remove [this videoId](https://github.com/tjallingt/react-youtube/blob/rewrite/src/YouTube.js#L139-L141) check, [it's already handled](https://developers.google.com/youtube/iframe_api_reference#onError) by the underlying YouTube API and passed to `props.onError` w/ a status code. I like the idea of throwing an error regardless of whether `props.onError` is being listened to, but I think that should go into `youtube-player` and not `react-youtube`. Thoughts?

- `props.opts` needs to be cloned before being passed to youtubePlayer [here](https://github.com/tjallingt/react-youtube/blob/rewrite/src/YouTube.js#L127). `youtube-player` mutates the `options` object [here](https://github.com/gajus/youtube-player/blob/master/src/index.js#L98), which means the `props.opts` object being passed into a `react-youtube` instance is being mutated, which just leads to a menagerie of issues.

You can clone it using spread properties, so

```js
this._internalPlayer = youTubePlayer(this._containerId, this.props.opts);
```

becomes

```js
this._internalPlayer = youTubePlayer(this._containerId, { ...this.props.opts });
```

After that's fixed, let's squash and merge!

**Comment by tjallingt** [comment]
> Let's remove this videoId check, it's already handled by the underlying YouTube API and passed to props.onError w/ a status code, specifically 2. I like the idea of throwing an error regardless of whether props.onError is being listened to, but I think that should go into youtube-player and not react-youtube. Thoughts?

Completely agree, i forgot that youtube handles passing a null

**Comment by troybetz** [comment]
Thanks @tjallingt! Going to start rewriting the tests today, let me know if you want to be added to this project to help out some more!

**Comment by tjallingt** [comment]
Sure I can help out if you need it sometimes (although like i mentioned before I don't have much experience with tests :S)

**Comment by troybetz** [comment]
For sure, just added you as a collaborator. No obligations, but if you want to help out every once in a while feel free!

**Pull request merged**
