### PR TITLE
Add onPlaybackRateChange event handler

### PR DESCRIPTION
**Pull request by jcshih**
Just hooks in onPlaybackRateChange event

### CODE REVIEW

**Comment by tjallingt** [comment]
Could you add the `onPlaybackQualityChange` event as well so we have full compatibility with the youtube iframe api?

**Comment by jcshih** [comment]
Done :grinning: I think the only event left is onApiChange, but I don't quite understand it, so I'll leave it alone for now.

**Comment by tjallingt** [comment]
Yea the

**Comment by tjallingt** [comment]
Great!
The `onApiChange` event is a bit strange indeed, I don't think there will be many people who will use it so for now it's fine.
Thanks for your work :+1:

**Pull request merged**
