### PR TITLE
Add host prop to set host for player frame

### PR DESCRIPTION
**Pull request by T0astBread**
Using this prop you can set the host of the player frame to any host you like.
Practical use case: streaming from www.youtube-nocookie.com

### CODE REVIEW

**Comment by tjallingt** [comment]
Hey,

Thanks for the PR but it looks like it was already possible to pass this option through the opts prop like so
```jsx
<YouTube
  videoId="2g811Eo7K8U"
  opts={{
    host: 'www.youtube-nocookie.com'
  }}
  onReady={this._onReady}
/>
```
I also can't find any documentation on this option on the official reference: https://developers.google.com/youtube/iframe_api_reference 

Where did you learn about this option?

Althogether im not sure this is a very useful change, but maybe if you can explain more about this I'll reconsider 😕

**Comment by T0astBread** [comment]
Okay, this might actually be more useless than I originally thought.

I saw this being used on the DuckDuckGo search results page and I thought I had read something about it being a version of the YouTube player that does not immediately track you when the player is loaded or something like that but it turns out those sources are all really old and very likely out of date.

My guess now is they removed this service and just kept the API up to avoid breaking changes. (However, that still begs the question why DDG uses it...)

I'll try to get additional information on this and if I find anything I'll post it here. (Sorry for potentially wasting your time with this.)

**Comment by T0astBread** [comment]
I'll close the PR since this functionality (regardless of the usefulness) is already implemented.

**Comment by tjallingt** [comment]
> Sorry for potentially wasting your time with this.

Don't worry about it, I appreciate anyone spending their time making this package better. :smile:

**Comment by tjallingt** [comment]
Wrong button on phone mb

**Comment by T0astBread** [comment]
I asked and DDG doesn't know what youtube-nocookie is either https://twitter.com/DuckDuckGo/status/1024911022820413441

**Pull request closed without merging**
