### PR TITLE
Adds videoId prop

### LINKED ISSUE #45: Add `videoId` prop
Tired of having to write `https://www.youtube.com/watch?v=${videoId}` every time.

### PR DESCRIPTION
**Pull request by troybetz**
Fixes #45

### CODE REVIEW

**Comment by troybetz** [comment]
@tjallingt should we just deprecate/remove `props.url`? Honestly don't even remember why I preferred it initially

**Comment by tjallingt** [comment]
Yea I think so...
The `props.url` is nice to have for the less tech savy people but I don't think those people will be using React anyway.
And people who use an external API (like the YouTube Data API) are more likely to receive a `videoId` than a video url.
Lastly anyone who does wants to use a url can just use `getYouTubeID(url)` (perhaps you can even put that in the readme)

**Comment by troybetz** [comment]
👍opening a pr for it right now

**Comment by troybetz** [comment]
Closes #45

**Pull request merged**
