### PR TITLE
Use prop-types instead of React.PropTypes

### PR DESCRIPTION
**Pull request by tristanoneil**
See [here](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes) for more info.

### CODE REVIEW

**Comment by gpminsuk** [comment]
+1 Please accept this

**Comment by RobertFischer** [comment]
What's the advantage of this?

**Comment by goto-bus-stop** [comment]
Accessing React.PropTypes is deprecated in react 15.5 and logs a deprecation warning.

**Comment by tjallingt** [comment]
Great thanks for the pull request! 🎉

**Pull request merged**
